### ISSUE TITLE
Media Explorer doesn't find files

### ISSUE THREAD

**Issue by and471** [media-explorer/media-explorer#10]
I am not using Tracker however according to the Media Explorer documentation, mex should find my music in ~/Music etc.

However when I load mex, it doesn't find anything

**Comment by ghost** [comment]
How did you configure Tracker and Grilo to compile them ?

**Comment by and471** [comment]
Well I didn't :)

I just compiled the latest version of Grilo from GIT

**Comment by ghost** [comment]
Oops I meant Media-explorer and Grilo, sorry.

I guess you picked up the lastest grilo 0.1.x ?
Grilo 0.2 (which is git master now) won't work (you shouldn't be able to compile Media-explorer).

If you don't have/want Tracker then configure Media-explorer with --enable-library --disable-tracker.

**Comment by ghost** [comment]
According to our discussion on IRC, the issue seems to be solve.
