### ISSUE TITLE
mex_tool_provider_remove_actor should return to home screen

### ISSUE THREAD

**Issue by jpwhiting** [media-explorer/media-explorer#104]
When a conversation ends in mex telepathy plugin I'm calling mex_tool_provider_remove_actor to hide my ui.  This works fine, but it doesn't go back to the home screen.

adding 

mex_show_home_screen(data); 

to the end of mex_tool_remove_actor_cb solves this issue here.

**Comment by thos** [comment]
Thanks for reporting this issue, I've pushed the fix you recommended to master.
