### ISSUE TITLE
Search results grid view missing title and menu

### ISSUE THREAD

**Issue by ghost** [media-explorer/media-explorer#112]
When search results are displayed in the grid there is no menu and no title in the grid view.

**Comment by Cwiiis** [comment]
The menu was ommitted purposefully by designers - adding it back is as
trivial as just setting the default sort functions when registering the
model info.

**Comment by dlespiau** [comment]
Just asked Victor and he was saying that we should have a least a tile like "Search" or "Results" for the column and. For the sort funcs we can use the alphabetic order for now until we get other sort funcs

**Comment by ghost** [comment]
I got that working, but still fighting the mess of aggregate model + model manager + explorer...

**Comment by ghost** [comment]
Fixed in eaf9d32203d342e934557c3497599ba55b138001
