### ISSUE TITLE
new icons request (telepathy)

### ISSUE THREAD

**Issue by jpwhiting** [media-explorer/media-explorer#119]
The media-explorer telepathy-plugin is almost complete. http://cgit.collabora.com/git/media-explorer.git/ telepathy-plugin branch.  And as such we would like to request a few icons to be added to the mex theme.  Namely:

video call
audio call
add contact
contacts
video stop
video start
hangup

similar icons are available in the meego-ux-theme package under the im app folder if that helps as as starting point.

thanks

**Comment by semiot** [comment]
Hi there, 

We're currently working out a project plan for upcoming visual work, we'll look at how these fit into our larger theming plans! 

One thing to note, the meego-ux-theme package isn't actually open source so we'd advise against integrating those icons here. 
- Victor

**Comment by jpwhiting** [comment]
Ah, ok good to know.  No so far we are just using icons in the mex theme. MediaStop, MediaPlay, etc.

Thanks

**Comment by jpwhiting** [comment]
Thanks for the icons you got us today, that looks much better imo.  Could you also do ones for:

mute
unmute

I have some I did myself in there, but matching ones would look much better. :)

**Comment by semiot** [comment]
Think I've delivered all required, here, Jeremy can you confirm? If so I'll close....

**Comment by jpwhiting** [comment]
You sure have.  Thanks so much.
