### ISSUE TITLE
Advanced Mouse support

### ISSUE THREAD

**Issue by olethanh** [media-explorer/media-explorer#12]
It would be nice if the scroll wheel was supported and if you could pass in fullscreen mode by double clicking when playing a video.

**Comment by dlespiau** [comment]
Lionel added the fullscreen on double click one when playing a video

**Comment by ghost** [comment]
Yep, the scrolling would definitely be a bit more of work (not too much), but I don't know if someone can have a look at that at the moment.

**Comment by semiot** [comment]
Consolidating under Issue #92: Mouse Interaction Model
