### ISSUE TITLE
placeholder image for optical disk

### ISSUE THREAD

**Issue by ghost** [media-explorer/media-explorer#128]
It would be nice to have a different place holder image for optical disks

**Comment by semiot** [comment]
Have asked Cyrene to whip something up for this while also looking at the video chat stuff, should have some assets next week hopefully. Stay tuned.

**Comment by semiot** [comment]
Cyrene has created a Disc for this purpose. Have emailed it to use. Icon coming soon.

**Comment by semiot** [comment]
Placeholder + Eject icon now in Thomas' inbox...
