### ISSUE TITLE
Port dbus code from dbus-glib to gdbus

### ISSUE THREAD

**Issue by dlespiau** [media-explorer/media-explorer#131]
And thus remove the dependency on dbus-glib

**Comment by rbradford** [comment]
The main problem here is that the code generation for gdbus is only available in glib master (not 2.28.)

**Comment by thos** [comment]
All of the code apart from the rebinder applet has now been moved to GDBus. I think the rebinder applet is going to be removed, so once that is done, this issue can be closed.

**Comment by dlespiau** [comment]
Fixed in 5ccaa0c8c617c648f3698efddbca48231ca2cc8d
