### ISSUE TITLE
MEX needs to set itself as the preferred call handler

### ISSUE THREAD

**Issue by treitter** [media-explorer/media-explorer#136]
If both Empathy and MEX are running, and we start a video or audio call with a Telepathy contact, Empathy's call handler pops up to handle the call (not MEX's).

Similarly, MEX needs to set itself as the preferred handler when it accepts an incoming call.

**Comment by drf** [comment]
a32bfb7e7162c4b299046e37b85b2f05cc9a0115 should fix at least a big part of the problem
