### ISSUE TITLE
MEX Tp plugin fails to refresh its contact list on "clean" start

### ISSUE THREAD

**Issue by treitter** [media-explorer/media-explorer#137]
If MEX is started with Mission Control and the Connection Managers not already running,
- MC and the CMs start (as they should)
- but the Contact list never grows beyond its initial zero contacts

If you close and immediately re-open MEX after that, it works as expected.

So there just must be some signals that the Telepathy plugin is ignoring.

**Comment by jpwhiting** [comment]
I am able to recreate this issue pretty easily on my machine.  Using upstream master telepathy-glib fixes the issue though.
