### ISSUE TITLE
Compile Error with Mx

### ISSUE THREAD

**Issue by and471** [media-explorer/media-explorer#14]
When I try to compile media-explorer with mx (1.1.12 as specified in configure.ac) I get the following error:

./.libs/libmex-0.2.so: undefined reference to `mx_kinetic_scroll_view_get_scroll_policy'
./.libs/libmex-0.2.so: undefined reference to`mx_kinetic_scroll_view_set_scroll_policy'

**Comment by ghost** [comment]
You need the lastest Mx in git master for that.

**Comment by and471** [comment]
Ok, maybe you should bump the version required in configure.ac :)

Also could you do me a favour, something is not quite right with clutter-project.org, I can't clone any git repositories, it just hangs forever, could you package up the latest GIT? I would really appreciate it.

**Comment by ghost** [comment]
The Mx version required hasn't been released/tagged yet, if you're using jhbuild-mex and rebuild Mx it should point to the last master version and everything should be fine (tell us if it's not the case).
I will keep the issue open till we release a new version of Mex which will depend on the right version of Mx.

Regarding the clutter repository, most of them has been moved to the git.gnome.org with exception of Mx which is on github for now. Once again, if you use the jhbuild-mex everything should be checked out from the right repository.

**Comment by dlespiau** [comment]
@and741: The Mx git repo is actually there: https://github.com/clutter-project/mx the one on clutter-project.org is closed even if there's no hint about it, sorry about that.

**Comment by and471** [comment]
Thanks it works fine now :)
