### ISSUE TITLE
Outdated FSF address

### ISSUE THREAD

**Issue by hadess** [media-explorer/media-explorer#140]
rpmlint says:
mex.x86_64: E: incorrect-fsf-address /usr/share/mex/webremote/index.html
mex.x86_64: E: incorrect-fsf-address /usr/share/doc/mex-0.1.6/COPYING

**Comment by dlespiau** [comment]
Fixed in 45caed5.

**Comment by hadess** [comment]
From rpmlint again:
media-explorer-debuginfo.x86_64: E: incorrect-fsf-address
/usr/src/debug/media-explorer-0.3.2/applets/webremote/tracker-client.h
media-explorer-debuginfo.x86_64: E: incorrect-fsf-address
/usr/src/debug/media-explorer-0.3.2/applets/webremote/tracker-client.c

**Comment by dlespiau** [comment]
Sigh, a sed that went wrong.

Should be fixed in by a8b0322199e6fcbced275b6813237581e50211df
