### ISSUE TITLE
Rename media explorer binary

### ISSUE THREAD

**Issue by ghost** [media-explorer/media-explorer#142]
Apparently our binary filename collide with the package texlive-lang-polish, also providing /usr/bin/mex.

Suggestions for a new binary name ?

**Comment by jpwhiting** [comment]
Is media-explorer out of the question for some reason? I always wondered why it wasn't named that anyway.

**Comment by ghost** [comment]
media-explorer might be a bit generic isn't it ?
But if everyone's ok with that...

**Comment by dlespiau** [comment]
I guess the main reason is that I found media-explorer a bit dull and went with mex instead. To be honest, it needs a better than than any of those :D

**Comment by dlespiau** [comment]
That bug was already closed WONTFIX as, really, I don't care about an obscure package in Debian :p

**Comment by ghost** [comment]
It now collides with the mathlab package on some distro, we really to change the binary name.

**Comment by dlespiau** [comment]
Fine, fine :p changed the binary and desktop file name to media-explorer.

**Comment by ghost** [comment]
Sorry, we're having issues with data files which aren't located in the right directory anymore.
/usr/share/mex/ should now be /usr/share/media-explorer

**Comment by ghost** [comment]
Fixed in 4ac9fec6800eb5584f6fb2d45fbfbd6fbf37f564 and 77e4443a3f4dd99d5c47fe84e5a817d1c8469b65.
