### ISSUE TITLE
Mex needs to handle being a single instance application

### ISSUE THREAD

**Issue by ghost** [media-explorer/media-explorer#143]
When you do "Open with Media explorer" it will currently try and launch a new instance of mex

This also happens when you select multiple files in nautilus and select "open with media explorer" 

mx_application_is_running, mx_application_add_action ..etc

**Comment by thos** [comment]
Mex is already single instance since it will check if there is an existing implementation of the MexPlayer interface on the bus. However, the new instance will need to communicate the name of the file to the existing instance.

**Comment by ghost** [comment]
Indeed, which is why this is entitled "handle" being a single instance.

**Comment by thos** [comment]
I'm looking into this issue, it may need some enhancements to MxApplication to allow it to pass parameters between applications.

**Comment by dlespiau** [comment]
Haven't you pushed this in commit 28e4c7d ?

**Comment by thos** [comment]
Yes, this is fixed with commit 28e4c7d.

**Comment by ghost** [comment]
This doesn't work if the application is not already running, there is also something missing that means that nautilus doesn't realise the file open has been handled successfully. i.e. you get the spinner

**Comment by thos** [comment]
What doesn't work if the application is not already running?

The issue with the spinner sounds like the start up notification is not being cancelled.

**Comment by ghost** [comment]
1) Mex isn't running
2) Select a bunch of files in nautilus and open with media explorer
3) Mex doesn't launch properly

**Comment by thos** [comment]
I've just pushed a commit to media-explorer and to mx that fixes the spinner issue and appears to fix the issue with opening multiple files.
