### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by tuxeric** [media-explorer/media-explorer#15]
should i consider changing my graphics adapter?

i have a
0a:04.0 VGA compatible controller: ATI Technologies Inc ES1000 (rev 02)

eric-gentoo ~ 0 $ libtool e gdb /usr/local/media-explorer/bin/mex 
GNU gdb (Gentoo 7.2 p1) 7.2
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i686-pc-linux-gnu".
For bug reporting instructions, please see:
http://bugs.gentoo.org/...
Reading symbols from /usr/local/media-explorer/bin/mex...done.
(gdb) run
Starting program: /usr/local/media-explorer/bin/mex 
[Thread debugging using libthread_db enabled]

Program received signal SIGSEGV, Segmentation fault.
0xb752df58 in XF86DRIQueryExtension () from //usr/lib/opengl/ati/lib/libGL.so.1
(gdb)

**Comment by dlespiau** [comment]
People have clutter running on ATI hardware, you should probably try to get one of the Clutter tests running first. Which ATI driver are you using, I remember people having problem with the official driver but the Gallium one is able to run GNOME shell and seems a better option. Also, can we have the full backtrace to see where you come from? probably from inside one of the clutter initialization function.

If you can reproduce the segfault with says tests/interactive/test-actors from the Clutter repository, I'll be closing this bug and you should seek help from #clutter on irc.gimp.org or file a bug in Clutter's bugzilla https://bugzilla.gnome.org/enter_bug.cgi?product=clutter

**Comment by tuxeric** [comment]
i can reproduce it every time i try to start mex

i switched to xorg, frrom the ati amd
eric-gentoo ~ 0 $ eselect opengl show
xorg-x11

and it seems to be indeed a problem with clutter

ric-gentoo ~ 0 $ libtool e gdb /usr/local/media-explorer/bin/mex
GNU gdb (Gentoo 7.2 p1) 7.2
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i686-pc-linux-gnu".
For bug reporting instructions, please see:
http://bugs.gentoo.org/...
Reading symbols from /usr/local/media-explorer/bin/mex...done.
(gdb) run
Starting program: /usr/local/media-explorer/bin/mex 
[Thread debugging using libthread_db enabled]
failed to create drawable

(mex:300): Clutter-CRITICAL *_: Unable to initialize Clutter: Unable to select the newly created GLX context
*_
Cogl-glx:ERROR:./winsys/cogl-xlib.c:87:_cogl_xlib_set_display: assertion failed: (_cogl_xlib_display == NULL)

Program received signal SIGABRT, Aborted.
0xb7fe1424 in __kernel_vsyscall ()

i put the traces up
http://62.231.126.75/mex/

ati is the first segfault i got
xorg is the one with the xorg drivers

**Comment by dlespiau** [comment]
Ok, that's definitely a problem with Clutter then. Are you using Clutter master or the 1.6 branch? The 1.6 branch is the stable one and should be used for now.

**Comment by dlespiau** [comment]
Hey again,

Another source has been able to reproduce a similar issue. For him, Clutter 1.6 works with the proprietary drivers but not with the Gallium one. In any case, this is not an issue with mex itself but with either Clutter setting up GLX or the driver itself. There nothing we can do at the mex level.

The next step would be to file a bug in Clutter with proper backtraces (bt in gdb) to see where it's segfaulting with the proprietary drivers and where it bails out for the free one. Please include more information as the card chipset and versions of the drivers too, anything that can help.  Be warned that the answer at the Clutter level can be "File a bug against your drivers, it works well on others".

Closing this one then, next step in your journey https://bugzilla.gnome.org/enter_bug.cgi?product=clutter :p

**Comment by jku** [comment]
Also, fglrx driver is known to crash like this if radeon module is loaded (basically a configuration problem).

See e.g. the beautiful hack mozilla folks do in that case: https://bugzilla.mozilla.org/attachment.cgi?id=515226&action=diff#a/gfx/thebes/GLContextProviderGLX.cpp_sec2
