### ISSUE TITLE
Store the plugin priority inside a  the plugin itself

### ISSUE THREAD

**Issue by dlespiau** [media-explorer/media-explorer#156]
Right now, we still have the awful hack to start the name the plugins' DSO with a number to load them in the order we want.

What would be quite a bit nicer is a start having a small structure inside the plugins with a variety of information (name, authors, license, ...) including a "priority", basically the same number than we have now in the name of the DSO.

Additional points if we have some sort of "introspection" a la gst-inspect to list plugins (with the right order for instance) or to show more details about a plugin say:

$ media-explorer --list-plugins
...

$ media-explorer --show-plugin tracker

**Comment by dlespiau** [comment]
Actually, while having a priority for loading plugins with a certain order, the order of the models to get the columns seems to belong to an other object (say the models) eg. a plugin loaded last can still want to display a model in the first column

**Comment by thos** [comment]
The columns of the home screen are determined by categories, so I think the priority (i.e. order) should be attached to these. However, having some sort of plugin metadata available would be nice anyway.

**Comment by dlespiau** [comment]
Made some progress for this, no more number in the .so and we now have a MexPluginDescription structure as the entry point.

The only bit missing is to order the plugins by priority before loading them.

**Comment by dlespiau** [comment]
The plugin manager now respsects the priority field of MexPluginDescription, that a good enough state to close this bug, the need to have a mex-inspect binary is very limited and does not give anything interesting,
