### ISSUE TITLE
Watch from beginning action doesn't work properly anymore

### ISSUE THREAD

**Issue by ghost** [media-explorer/media-explorer#160]
The 'watch from beginning' action picks the wrong content when calling the player.
This is due to the fact that we're using the same action for every menu/item and because the content is set on the action as a qdata parameter.

Whatever 'watch from beginning' button you hit, it's always the same content being player, which is the last one set on the MexAction (when the last item/tile has been created).

**Comment by dlespiau** [comment]
Fixed in master and 0.2 branch (commit 09924c24c)
