### ISSUE TITLE
Remove the rebinder utility

### ISSUE THREAD

**Issue by thos** [media-explorer/media-explorer#163]
As discussed, it may be time to remove the rebinder application. It is unlikely to work on most Linux distributions, since it requires user read permissions on the input devices. We also have support for lirc, which can handle configuration of many remote controls, including evdev based devices. Additionally, we now have support  for multiple buttons for each action, which means many remote controls will work automatically. The welcome screen is also now not included in the rebinder.

**Comment by ghost** [comment]
We should provide a udev remapping file per hardware remote.

**Comment by dlespiau** [comment]
Fixed in 5ccaa0c8c617c648
