### ISSUE TITLE
Move "display-item-count" and "always-visible" properties

### ISSUE THREAD

**Issue by thos** [media-explorer/media-explorer#166]
Move "display-item-count" and "always-visible" properties from MexGenericModel to MexModelCategoryInfo

**Comment by chiragharendra** [comment]
b04ae4aa Move applied, please review.

**Comment by chiragharendra** [comment]
5fc71f5d, Move re-applied, please review

**Comment by thos** [comment]
I've removed the unrelated changes and made sure the c_info variable was initialised in mex_explorer_should_column_be_visible in commit dd30270 and pushed the commit to master.
