### ISSUE TITLE
Create a package for Fedora 15

### ISSUE THREAD

**Issue by dlespiau** [media-explorer/media-explorer#17]
To get people to test mex more easily, It'd be nice to have a Fedora 15 package.

**Comment by mstoykov** [comment]
I'm on the same opinion ^_^.

**Comment by hadess** [comment]
Doing that now.

**Comment by hadess** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=719103

**Comment by hadess** [comment]
I'll close this, feel free to follow the bugzilla for updates.
