### ISSUE TITLE
Telepathy plugin crashes when no web cam is available

### ISSUE THREAD

**Issue by thos** [media-explorer/media-explorer#171]
Attempting to start a call without a web cam causes the plugin to crash.
1.  0x00007fffdc5dd07e in tp_channel_get_requested (self=0x0) at channel.c:2177
2.  0x00007fffdcda3983 in mex_telepathy_channel_on_contact_fetched (connection=0x1cfe000 [TpConnection], n_contacts=1, contacts=
   0x359db00, n_failed=0, failed=0x359e900, fetched_error=0x0, user_data=0x38e4060, weak_object=0x0)
   at telepathy/mex-telepathy-channel.c:1180
3.  0x00007fffdc624dfd in contacts_context_continue (c=0x33d42d0) at contact.c:1814
4.  0x00007fffdc6297d8 in contacts_get_attributes (context=0x33d42d0) at contact.c:3964
5.  0x00007fffdc624f6d in contacts_context_continue (c=0x33d42d0) at contact.c:1847
6.  0x00007fffdc624f8a in contacts_context_idle_continue (data=0x33d42d0) at contact.c:1855
7.  0x0000003cf48427ed in g_main_dispatch (context=0x7fffe00008c0) at gmain.c:2441
8.  g_main_context_dispatch (context=0x7fffe00008c0) at gmain.c:3014
9.  0x0000003cf4842fc8 in g_main_context_iterate (context=0x7fffe00008c0, block=<optimized out>, dispatch=1, self=<optimized out>)
   at gmain.c:3092
10.  0x0000003cf484360d in g_main_loop_run (loop=0x1c81840) at gmain.c:3300
11. 0x00007ffff738c12c in clutter_main () at ./clutter-main.c:676
12. 0x00007ffff7ac6d0f in mx_application_run (application=0x7fffe8005e70 [MxApplication]) at ../mx/mx-application.c:704
13. 0x000000000040dc7e in main ()

**Comment by jpwhiting** [comment]
Thanks for catching that.  I just committed a fix to master branch that fixes it here.
