### ISSUE TITLE
webremote debug messages

### ISSUE THREAD

**Issue by ghost** [media-explorer/media-explorer#178]
replace all the debug output stuff in the webremote with MEX_DEBUG goodness

**Comment by chiragharendra** [comment]
03a67f8 - fixed in commit, please review

**Comment by ghost** [comment]
As this replaces the old method of debug output please remove the redundant code as well.

1) self->opt_debug
2) if (self->opt_debug)

**Comment by chiragharendra** [comment]
Redundant code removed, please review changes.

**Comment by ghost** [comment]
looks fine to me once the alignment is done, feel free to close this issue when the fix is in master
