### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by guiodic** [media-explorer/media-explorer#19]
Hi!

I'm trying to build mex on ubuntu 11.04. I installed the requested dependencies (please, note your debian/control is insufficient [*]) but I still have a strange error:

Please check the build log here: https://launchpadlibrarian.net/73009464/buildlog_ubuntu-natty-i386.media-explorer_0.1.0-1~0guiodic6_FAILEDTOBUILD.txt.gz

make[4]: Entering directory `/build/buildd/media-explorer-0.1.0/shell'
\
# source='mex-main.c' object='mex-main.o' libtool=no

gcc -DHAVE_CONFIG_H -I. -I..    -I.. -I../mex -I../applets/rebinder -pthread -I/usr/include/glib-2.0 -I/usr/lib/i386-linux-gnu/glib-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/libpng12 -I/usr/include/atk-1.0 -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/dbus-1.0 -I/usr/lib/i386-linux-gnu/dbus-1.0/include -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libsoup-2.4 -I/usr/include/libxml2 -I/usr/include/mx-1.0 -I/usr/include/clutter-1.0 -I/usr/include/cairo -I/usr/include/json-glib-1.0 -I/usr/include/pixman-1 -I/usr/include/gstreamer-0.10 -I/usr/include/rest-0.7 -I/usr/include/grilo-0.1    -DG_LOG_DOMAIN=\"Mex\" -DPKGDATADIR=\""/usr/share/mex/shell"\"  -g -O2 -g -O2 -g -O0 -c mex-main.c
mex-main.c:40:25: fatal error: mex-version.h: No such file or directory
compilation terminated.

[*] dependencies needed are: 
Build-Depends: gnome-common, cdbs, debhelper, gtk-doc-tools, libglib2.0-dev (>= 2.26.0), libclutter-gst-dev (>= 1.3.6), libmx-dev (>= 1.2.0), libsoup2.4-dev, libtracker-sparql-0.10-dev, libgdk-pixbuf2.0-dev, librest-dev (>= 0.7.0), libdbus-glib-1-dev, libgrilo-0.1-dev (>= 0.1.15), libxtst-dev, libgudev-1.0-dev

**Comment by guiodic** [comment]
mex-version.h is in .gitignore:

https://github.com/media-explorer/media-explorer/blob/3a4370886150fbdf83c0d4787e7c9d89e68f2d21/shell/.gitignore

**Comment by ghost** [comment]
mex-version.h is a generated header, that's why it's in .gitignore.
Are you building the package using an out of tree build ?

The debian directory is supposed to work on Debian Sid, it might not work for ubuntu.

**Comment by guiodic** [comment]
well, I workarounded the issue defining MEX_VERSION_GIT in the code, but I have another one: https://github.com/media-explorer/media-explorer/issues/20

**Comment by dlespiau** [comment]
Are you building from a git clone or from a release tarball? we might not dist it (and probably should not to require git at build time). Reopening, need to look into that.

**Comment by guiodic** [comment]
It was from a git clone. On Ubuntu launchpad should be impossible to use git at build time because security reasons.

**Comment by dlespiau** [comment]
Ok, so just checked and we do distribute the file in tarballs, as it should be.

Now if you want to package a version from git, what I would recommend is to generate a "make dist" tarball and use this tarball in your package. For instance, current master has "0.1.1" in the configure.ac (we make sure that the micro number is always odd in master) you can do a

$ make dist VERSION=0.1.1-git20110608

This will generate a mex-0.1.1-git20110608.tar.gz tarball with a mex-version.h you can use in your packaging. Hopefully this solves your problen of having to redefine MEX_VERSION_GIT by hand in the code/package.

HTH.
