### ISSUE TITLE
Video preview

### ISSUE THREAD

**Issue by ghost** [media-explorer/media-explorer#196]
When a video item is selected in the grid or column change from a thumbnail to a live preview of the video

**Comment by semiot** [comment]
That would be really cool. Question though, if its done over a network assuming there may be some latency issues to consider... need to hack it up to see how it feels?

**Comment by ghost** [comment]
I would envisage it as having a slight delay anyway, so it would only start playing the preview after being selected for say 2.5 seconds or so. 

We could also do the same with music items but with some sort of other visual indicator that it's a preview happening.

It shouldn't be difficult to do as we have all the components for this already so no harm in trying these things out.

**Comment by ghost** [comment]
feature added 99fcb4b6ffdac4a261dfd97f7bc43e9b13f3ca72
