### ISSUE TITLE
Mex doesnt see contents

### ISSUE THREAD

**Issue by guiodic** [media-explorer/media-explorer#20]
I succesfully builded mex, but it seems was unable to see grilo plugins:

GRL_DEBUG=plugin-registry:debug mex
(mex:12272): Grilo-DEBUG: [plugin-registry] grl-plugin-registry.c:188: $GRL_PLUGIN_RANKS is not set, using default ranks.

(mex:12272): Grilo-WARNING **: [plugin-registry] grl-plugin-registry.c:712: There is no information about a plugin with id 'grl-tracker'

(mex:12272): Mex-WARNING **: Tried to load specified grilo plugin: grl-tracker but failed: There is no information about a plugin with id 'grl-tracker'

(mex:12272): Grilo-WARNING **: [plugin-registry] grl-plugin-registry.c:712: There is no information about a plugin with id 'grl-local-metadata'

(mex:12272): Mex-WARNING **: Tried to load specified grilo plugin: grl-local-metadata but failed: There is no information about a plugin with id 'grl-local-metadata'

(mex:12272): Grilo-WARNING **: [plugin-registry] grl-plugin-registry.c:712: There is no information about a plugin with id 'grl-vimeo'

(mex:12272): Mex-WARNING **: Tried to load specified grilo plugin: grl-vimeo but failed: There is no information about a plugin with id 'grl-vimeo'

(mex:12272): Grilo-WARNING **: [plugin-registry] grl-plugin-registry.c:712: There is no information about a plugin with id 'grl-lastfm-albumart'

(mex:12272): Mex-WARNING **: Tried to load specified grilo plugin: grl-lastfm-albumart but failed: There is no information about a plugin with id 'grl-lastfm-albumart'

(mex:12272): Grilo-WARNING **: [plugin-registry] grl-plugin-registry.c:712: There is no information about a plugin with id 'grl-youtube'

(mex:12272): Mex-WARNING **: Tried to load specified grilo plugin: grl-youtube but failed: There is no information about a plugin with id 'grl-youtube'

(mex:12272): Grilo-WARNING **: [plugin-registry] grl-plugin-registry.c:712: There is no information about a plugin with id 'grl-filesystem'

(mex:12272): Mex-WARNING **: Tried to load specified grilo plugin: grl-filesystem but failed: There is no information about a plugin with id 'grl-filesystem'

(mex:12272): Grilo-WARNING **: [plugin-registry] grl-plugin-registry.c:712: There is no information about a plugin with id 'grl-upnp'

(mex:12272): Mex-WARNING **: Tried to load specified grilo plugin: grl-upnp but failed: There is no information about a plugin with id 'grl-upnp'

(mex:12272): Mex-WARNING **: Error playing content: No URI set

**Comment by guiodic** [comment]
cat $HOME/.config/mex/mex.conf

[grilo-plugins]
enabled=grl-tracker;grl-local-metadata;grl-vimeo;grl-lastfm-albumart;grl-youtube;grl-filesystem;grl-upnp;

So, I expected to see something because grl-tracker or grl-filesystem

**Comment by ghost** [comment]
It looks like there is a problem with your Grilo installation. Grilo is not able to find any plugin.
Did you installed them ?

Try to run :
  $ grl-inspect

to list the installed plugins, if none appears you should look at the way you installed grilo/grilo-plugins.

**Comment by guiodic** [comment]
I installed it by the official ubuntu ppa of grilo-team, but later I rebuild it with tracker plugin enabled. You see some plugin are not configured (they need API code) but others like gst-filesystem seem are loaded correctly.

grl-inspect

guido@guido-laptop:~$ grl-inspect

(grl-inspect:12689): Grilo-WARNING **: [tracker-general] grl-tracker.c:228:     Configuration not provided! Using default configuration.

(grl-inspect:12689): Grilo-WARNING **: [youtube] grl-youtube.c:264: Configuration not provided! Cannot configure plugin.

(grl-inspect:12689): Grilo-WARNING **: [plugin-registry] grl-plugin-registry.c:551: Failed to initialize plugin: '/usr/lib/grilo-0.1/libgrlyoutube.so'

(grl-inspect:12689): Grilo-WARNING **: [flickr] grl-flickr.c:129: Missing configuration

(grl-inspect:12689): Grilo-WARNING **: [plugin-registry] grl-plugin-registry.c:551: Failed to initialize plugin: '/usr/lib/grilo-0.1/libgrlflickr.so'

(grl-inspect:12689): Grilo-WARNING **: [vimeo] grl-vimeo.c:103: Missing configuration

(grl-inspect:12689): Grilo-WARNING **: [plugin-registry] grl-plugin-registry.c:551: Failed to initialize plugin: '/usr/lib/grilo-0.1/libgrlvimeo.so'
grl-bookmarks:  grl-bookmarks
grl-gravatar:  grl-gravatar
grl-jamendo:  grl-jamendo
grl-podcasts:  grl-podcasts
grl-local-metadata:  grl-local-metadata
grl-metadata-store:  grl-metadata-store
grl-filesystem:  grl-filesystem
grl-lastfm-albumart:  grl-lastfm-albumart
grl-apple-trailers:  grl-apple-trailers

**Comment by ghost** [comment]
Ok, let's trace a bit then.
Could you run :
  $ strace mex 2> /tmp/traces_mex
and paste the result of :
  $ grep grilo /tmp/traces_mex

**Comment by guiodic** [comment]
I noted that using "search" it suggest some results (text), I think from youtube, but selecting them nothing appears.
This is what you asked:

guido@guido-laptop:~$ grep grilo /tmp/traces_mex 
open("/usr/lib/libgrilo-0.1.so.0", O_RDONLY) = 3
open("/usr/share/grilo-0.1/plugins", O_RDONLY|O_NONBLOCK|O_LARGEFILE|O_DIRECTORY|O_CLOEXEC) = 11
lstat64("/home/guido/.config/mex/grilo-system.conf", 0xbfd4775c) = -1 ENOENT (No such file or directory)
lstat64("/usr/share/mex/grilo-system.conf", {st_mode=S_IFREG|0644, st_size=64, ...}) = 0
open("/usr/share/mex/grilo-system.conf", O_RDONLY|O_LARGEFILE) = 12
read(12, "[grilo-plugins]\nenabled=grl-trac"..., 4096) = 122
(mex:12875): Mex-WARNING *_: Tried to load specified grilo plugin: grl-tracker but failed: There is no information about a plugin with id 'grl-tracker'
(mex:12875): Mex-WARNING *_: Tried to load specified grilo plugin: grl-local-metadata but failed: There is no information about a plugin with id 'grl-local-metadata'
(mex:12875): Mex-WARNING *_: Tried to load specified grilo plugin: grl-vimeo but failed: There is no information about a plugin with id 'grl-vimeo'
(mex:12875): Mex-WARNING *_: Tried to load specified grilo plugin: grl-lastfm-albumart but failed: There is no information about a plugin with id 'grl-lastfm-albumart'
(mex:12875): Mex-WARNING *_: Tried to load specified grilo plugin: grl-youtube but failed: There is no information about a plugin with id 'grl-youtube'
(mex:12875): Mex-WARNING *_: Tried to load specified grilo plugin: grl-filesystem but failed: There is no information about a plugin with id 'grl-filesystem'
(mex:12875): Mex-WARNING **: Tried to load specified grilo plugin: grl-upnp but failed: There is no information about a plugin with id 'grl-upnp'

**Comment by guiodic** [comment]
cat /usr/share/mex/grilo-system.conf

[grl-tracker]
per-device-source = true
browse-filesystem = true

**Comment by ghost** [comment]
Ok, I think I remember a problem with the grilo package for ubuntu, which is the xml files describing grilo plugins aren't packaged. So your /usr/share/grilo-0.1/plugins directory must be empty, is that right ?

**Comment by guiodic** [comment]
Yes, it is empty. I could copy the xml file from the source tarball. Let's try.

**Comment by guiodic** [comment]
well, I can see videos in filesystem and seems tracker works too. Thany you!
