### ISSUE TITLE
Ignore tiny files?

### ISSUE THREAD

**Issue by ghost** [media-explorer/media-explorer#202]
We should probably ignore files < 50KiB

**Comment by kidwm** [comment]
but how about pictures?

**Comment by thos** [comment]
Why should small files be ignored? What type of files?

**Comment by ghost** [comment]
Initially I thought images, if your image is < 50KiB it will look rubbish on screen anyway. It's because tracker recently indexed 1000's of thumbnails and icons and other rubbish.

**Comment by kidwm** [comment]
IMHO, then you should not feed tracker those rubbish.

**Comment by ghost** [comment]
Yes, Ideally tracker wouldn't be indexing those things, but we don't have control over tracker's preferences and the job of media explorer is to show items that you would want to view on a TV/large screen/lean back. A 64x64px icon is not one of those things and should excluded from the results imo.

**Comment by ghost** [comment]
Include in the tracker query something like image.. 'nfo:width' >= '100'

**Comment by dlespiau** [comment]
Yeah, excluding small (dimension wise, not file size :p) images makes sense to me, they will look horrible anyway if we try to display them.

We should have something equivalent for sound/music files, anything a few seconds long is unlikely to be very interesting to display in mex.

**Comment by thos** [comment]
A fix for this was pushed in commit 37da355.
