### ISSUE TITLE
Can't build with clutter 1.9

### ISSUE THREAD

**Issue by DimStar77** [media-explorer/media-explorer#205]
Clutter 1.9 no longer supports the 'winsys' variable in clutter-1.0.pc (since this commit http://git.gnome.org/browse/clutter/commit/configure.ac?id=bb9e452a36d7a4fe3ed2090c050d096c26aae988, where it was change to deprecated).

As such, building media-explorer with 1.9 fails to detec the proper flavor of clutter to be used (as per configure, this is the 'OS detection hack').

**Comment by thos** [comment]
Thanks for reporting this issue. It should be fixed in commit 4bc3082.
