### ISSUE TITLE
Detection of tracker-sparql-0.14 not implemented

### ISSUE THREAD

**Issue by DimStar77** [media-explorer/media-explorer#206]
Tracker is moving up, and unfortunately their .pc file is not named after an API version but after the tracker version.

So even without API changes it keeps on being no longer detected.

As far as I've tested, the change from 0.12 to 0.14 seems not to cause trouble for mex, so I simply extended configure.ac to also detect tracker-sparql-0.14 as a valid option.

**Comment by ghost** [comment]
b18a995883
