### ISSUE TITLE
Provide a way to disable the background video at compile time

### ISSUE THREAD

**Issue by dlespiau** [media-explorer/media-explorer#22]
For the MeeGo Netbook image, it's actually quite expensive to decode the idle video in the background and not strictly needed. We should provide a configure option to disable that idle video. Actually, probably even have the background video disabled when not on Intel CE 4100.

**Comment by rossburton** [comment]
Let's just disable it by default.

**Comment by dlespiau** [comment]
Pushed an --enable-idle-video option, we default to having the background loop video enabled, because it looks good :p
