### ISSUE TITLE
compile error in mex / mex-utils.c:151

### ISSUE THREAD

**Issue by bitflippersanonymous** [media-explorer/media-explorer#225]
mex-utils.c:151:32: error: too many arguments to function 'mx_style_load_from_resource'

MX commit  5b650c521ac4dbb31e37a3fc7708c8377fd8149d removed the Resouce argument from mx_style_load_from_resource.

  /\* Load the style */
  mx_style_load_from_resource (mx_style_get_default (),
                               mex_get_resource (),
                               "/org/media-explorer/MediaExplorer/style/style.css",
                               &error);

Could be jhbuild needs to pull a specific version of MX

**Comment by thos** [comment]
Thanks for reporting this issue, it has been fixed in commit 0dc5c41.
