### ISSUE TITLE
Avoid shipping non-free data in tarballs

### ISSUE THREAD

**Issue by vuntz** [media-explorer/media-explorer#229]
Some of the test data is not free, and it's an issue for downstreams willing to ship media explorer (as the source package will contain non free data).

tests/COPYING clearly mentions:

> The *.dat files in the test directory are copyrighted by Radio Times
> (http://www.radiotimes.com)
> 
> These files should only be used for for your own personal and non-commercial
> use and not for any commercial or other purposes, including advertising or
> selling any goods or services, including any third-party software applications
> available to the general public.

Would it be possible to not ship this data in the tarballs?

**Comment by ghost** [comment]
Bang and the non-free items are gone 20e19c2b5885638249f77688fba654327cfa962b
