### ISSUE TITLE
Tweaks for set-top box mode

### ISSUE THREAD

**Issue by rossburton** [media-explorer/media-explorer#231]
Guacamayo is using MEX as the sole UX, so we've several requirements:
- The power-off icon should do something that isn't quit - not entirely sure if it should be suspend, power off, or ask.
- the networks applet needs to come back

And probably more.  We could hack these in but obviously Upstream First is a better way so does anyone have any opinions on say how to configure what the "exit" icon does?

**Comment by nedrichards** [comment]
How about it shuts down when you press alt?

More seriously - it should do whatever will pass the following tests (in priority order):
1) Enters a state when the remote control can awake it alone
2) Returns to full operation fastest
3) Uses least power

As for how you configure it for the system itself (--standalone or somesuch) I have no opinion.

**Comment by thos** [comment]
The "power" icon is now a "close" icon (represented by an X) in the latest design. It probably makes sense to remove this when in set-top box mode because presumably the user would use a hardware button or remote control to turn off the device.

**Comment by dlespiau** [comment]
We have a notion of "profiles" in the configure script for these kind of things, I think it could make sense to have a profile per "product". The default one is "gnome", where we quit when pressing the power icon. we could add an "generic-stb" profile I guess (we have gnome, intelce and windows profiles right now).

**Comment by thos** [comment]
I've added a gsettings option to disable the close button. The default is for it to be visible, but this can be changed by a "vendor override" file.

We should discuss the network settings applet in a separate issue.
