### ISSUE TITLE
mex-lirc.c has unnecessary dependency on clutter-x11.h

### ISSUE THREAD

**Issue by tthef** [media-explorer/media-explorer#232]
The lirc code is not X11 specific, but it includes clutter-x11.h and uses the X11 CurrentTime define. I have patched it out in Guacamayo so we can build MediaExplorer for x11-less Clutter, the patch is here, https://github.com/Guacamayo/meta-guacamayo/blob/master/meta-guacamayo/recipes-multimedia/media-explorer/media-explorer/0001-mex-lirc-remove-dependency-on-ClutterX11.patch.

**Comment by thos** [comment]
Thanks for the patch, I have pushed it to master.
