### ISSUE TITLE
Thumbnailer failing to generate thumbnails due to premature timeout

### ISSUE THREAD

**Issue by tthef** [media-explorer/media-explorer#235]
In Guacamayo Mex was not generating thumbnails for the Sintel trailer movie (mp4); turns out the seek operation in the thumbnailer is not allowed enough time (in the specific case the randomly requested seek position is 39s and the seek to there needs about 8s to complete on).

I think the solution is to clamp the random seek position to something sensible, and to allow more time for the seek. A patch is at https://github.com/tthef/media-explorer/commit/6c2cf39adb52bf8d71282ae0696f9dfd333d540a.

**Comment by tthef** [comment]
Alternative solution is to use the keyframe search; seems to work on the limited selection of videos at my disposal, patch is at https://github.com/tthef/media-explorer/commit/62dd8ef17078b8e7ae1a1c8856429dff8fb5873d

**Comment by tthef** [comment]
Patches for this are in https://github.com/Guacamayo/media-explorer/commits/master (this is a consolidated branch with various Guacamayo fixes (issues #235, #236, #237, #238).

**Comment by thos** [comment]
Thanks for the patch, I've pushed it to master.
