### ISSUE TITLE
Facilitate building plugins/applets out of tree

### ISSUE THREAD

**Issue by tthef** [media-explorer/media-explorer#236]
For Guacamayo I'd like to be able to build custom plugins and applets out of tree; this requires installing libmex headers and providing a pkgconfig file; patch: https://github.com/tthef/media-explorer/commit/99783296892fcb38bc9b10d360aa1d635f6dae16

**Comment by tthef** [comment]
Patches for this are in https://github.com/Guacamayo/media-explorer/commits/master (this is a consolidated branch with various Guacamayo fixes (issues #235, #236, #237, #238).

**Comment by thos** [comment]
Since the API is not considered stable yet, it is probably best to keep plugins and applets in tree so that they can be kept up to date with any changes.
