### ISSUE TITLE
Rework Settings to use plugin modules instead applications

### ISSUE THREAD

**Issue by tthef** [media-explorer/media-explorer#237]
I am looking into resurrecting the Networks settings for Guacamayo, and there are couple of issues in the overall Settings mechanism that I think need improvement:
1. Make Settings extensible; at present the Settings consist of a hard-coded list of desktop files, so adding new settings requires patching Mex,
2. Make it all in-process. The use of separate processes requires for the target platform to provide windowing services to manage window placement/size and overall focus. Having the settings UIs in process would eliminate this need and also make it possible to integrate it all more tightly with the Mex Shell.

Since Mex already has a plugin system, my suggestion would be to make use of that. Something like:
- Define MexInfoBarComponent interface; plugins extending MexInfoBar would implement this within the GObject type they
  instantiate,
- MexInfoBarComponent API would facilitate both inserting custom elements into the info bar and extending the standard
  Settings UI,
- MexInfoBar would use MexPluginManager::plugin-loaded signal to get what it needs.

What do you think?

**Comment by tthef** [comment]
Patches for this are in https://github.com/Guacamayo/media-explorer/commits/master (this is a consolidated branch with various Guacamayo fixes (issues #235, #236, #237, #238).

**Comment by thos** [comment]
The branch with these patches has been merged into master.
