### ISSUE TITLE
Add an option to the internal thumbnailer to save the thumbnails in JPEG

### ISSUE THREAD

**Issue by dlespiau** [media-explorer/media-explorer#25]
We already are out of the thumbnailing spec and our thumbnails should be considered as internal cache anyway. This means we can now save our thumbnails in JPEG to save disk space. Provide an option in some global configuration key file to tweak that, say something like:

[internal-thumbnailer]
format = jpeg

**Comment by ghost** [comment]
Pippin suggested the use of http://git.gnome.org/browse/gimp/tree/libgimpthumb to manage thumbnails.

**Comment by dlespiau** [comment]
The internal thumbnailer has been pushed to master and saves the thumbnails in JPEG. libgimpthumb would be useful if we were using the thumbnailing spec and pngs, but we're not anymore. Closing.
