### ISSUE TITLE
The slide show seems to leak memory

### ISSUE THREAD

**Issue by dlespiau** [media-explorer/media-explorer#26]
We have a bug report by mail that the slide show has hard time with large 16 MPixels photographs and that it is leaking large objects that makes the application look very sad.

Obviously, memory leaks are something we should fight with all our might.

**Comment by ghost** [comment]
We filed that bug from an external report. At the time we didn't had any performance / memory consumption analysis.
We fixed a bunch of bugs in Cogl/Clutter/Mex since then.

In the 0.1.4 release the slideshow doesn't seem to leak memory.
