### ISSUE TITLE
Hide File Extensions

### ISSUE THREAD

**Issue by hbons** [media-explorer/media-explorer#3]
This was added to the wiki, but it's really a bug. :)

"Just show me the name of the file. Only files that can be played will show up in the interface anway, no need to know if its .avi, .mpg, .jpg etc."

**Comment by ghost** [comment]
Problem reported : https://bugzilla.gnome.org/show_bug.cgi?id=645052
And fixed : http://git.gnome.org/browse/tracker/commit/?id=719e072c7aeaf59af697afc0f15bae0444d07b44

Should be in tracker 0.10.5

What's your tracker version ?
That might require a reindexation of your files if they were indexed before 0.10.5

**Comment by hbons** [comment]
I'm not running it. Just something that appears in screenshots.

**Comment by ghost** [comment]
Just check the lastest version of Tracker, it seems that the nie:title property isn't set anymore.
Looks like a regression, more investigation to come.

**Comment by ghost** [comment]
Ok, turns out the code filling the nie:title property is under compilation flag.
Need to compile Tracker with --enable-guarantee-metadata.

Closed :)
