### ISSUE TITLE
Web Remote - Android Wrapper

### ISSUE THREAD

**Issue by semiot** [media-explorer/media-explorer#39]
Create an app for the Web Remote to live it. The idea here is to make device discovery easier on the user.

**Comment by ghost** [comment]
All the essential features are now in, release to be made public as soon as I hear back regarding licences.

https://github.com/media-explorer/mex-android-remote

**Comment by semiot** [comment]
Any word on your license questions re: the android wrapper?

**Comment by ghost** [comment]
yep, it should be fine now. I'll make a release today/this week.
