### ISSUE TITLE
Background in Code

### ISSUE THREAD

**Issue by semiot** [media-explorer/media-explorer#45]
Currently the background used on the MEX home screen is a looping video file. To improve performance (and possibly to have some fun with visualizing usage) we'd like to recreate the video loop with Clutter.

**Comment by thos** [comment]
By having the background animation in code, we will also be able to remove the "idle-mode" property from MexPlayer.

**Comment by ghost** [comment]
We've got a first version of Pippin's background in clutter 84b4ae95bc988749828c642861f190bada55f423
