### ISSUE TITLE
Static Background

### ISSUE THREAD

**Issue by semiot** [media-explorer/media-explorer#49]
Create a simple png background for the homescreen for cases where the video is too much of a resourced drag.

**Comment by ghost** [comment]
Probably not needed once #45 is done

**Comment by thos** [comment]
We currently have a configuration option to disable the video and just display the background overlay over a black background. Would the proposed static background be different from this?

**Comment by ghost** [comment]
We have an infrastructure to use almost any kind of ClutterActor as a background for mex now, adding a static background would be trivial.

**Comment by semiot** [comment]
We'll just go with a standard black background. Closing this bug.
