### ISSUE TITLE
Thumbnailing problem with .ogg video files

### ISSUE THREAD

**Issue by ghost** [media-explorer/media-explorer#55]
Looks like we have a problem with .ogg files :

Mex-Message: Cannot generate thumbnail for file:///home/djdeath/Downloads/0402-Pippin.ogg: No thumbnailer available for "file:///home/djdeath/Downloads/0402-Pippin.ogg"

**Comment by rossburton** [comment]
Internal or tumbler?

**Comment by ghost** [comment]
tumbler

**Comment by dlespiau** [comment]
We only have the internal thumbnailer now, closing this.
