### ISSUE TITLE
Rebinder styling leaks into mex main app

### ISSUE THREAD

**Issue by ghost** [media-explorer/media-explorer#56]
On first boot the rebinder's style for certain buttons overrides the correct styling.

You can recreate this by:

Delete ~/.config/mex/out-of-box-done
Re-run mex
focus content item/settings/shutdown buttons

**Comment by thos** [comment]
I've fixed this in commit 40813a8 by ensuring the more generic rebinder style rules are within an actor with a Pane style class.
