### ISSUE TITLE
info-panel-simple singleton

### ISSUE THREAD

**Issue by ghost** [media-explorer/media-explorer#59]
At the moment the grid/columns create a new info panel instance for each content item, it might speed up things/use less memory if we re-used a single info panel as we do with the media player, as you never see multiple info panels at any one time.

On open info panel set the content and pack the info panel into the content box. On close unpack the info panel.

**Comment by ghost** [comment]
please review https://github.com/media-explorer/media-explorer/tree/info-panel-singleton

**Comment by thos** [comment]
I guess the main benefit of this will be to avoid loading the json file each time an info panel is created. In that case, it might be better to implement this as a feature inside the info panel. Adding and removing the info panel from the container each time it is shown or hidden will actually add an additional cost, so although this idea may save some time at start up, it may actually cause the showing and hiding of the info panel to become slower. I suggest we take a look at some sort of cache for the json file instead.
