### ISSUE TITLE
Segfault in mex-explorer.c

### ISSUE THREAD

**Issue by dlespiau** [media-explorer/media-explorer#64]
0x0013ffbe in mex_explorer_push_model (explorer=0x86aa7f8, model=0xb661ec50)
    at mex-explorer.c:863
863       if (MEX_IS_GRID (container))
#0  0x0013ffbe in mex_explorer_push_model (explorer=0x86aa7f8,

```
model=0xb661ec50) at mex-explorer.c:863
```
#1  0x00729783 in g_cclosure_marshal_VOID__OBJECT (closure=0x872f060,

```
return_value=0x0, n_param_values=2, param_values=0x8fbc590, 
invocation_hint=0xbfffd980, marshal_data=0x0) at gmarshal.c:638
```
#2  0x0070cf04 in g_closure_invoke (closure=0x872f060, return_value=0x0,

```
n_param_values=2, param_values=0x8fbc590, invocation_hint=0xbfffd980)
at gclosure.c:767
```
#3  0x0071f23a in signal_emit_unlocked_R (node=0x8637e50, detail=0,

```
instance=0x86aa7f8, emission_return=0x0, instance_and_params=0x8fbc590)
at gsignal.c:3252
```
#4  0x007281ec in g_signal_emit_valist (instance=0x86aa7f8, signal_id=133,

```
detail=0, var_args=0xbfffdb40 "P\304\373\b6\356\023") at gsignal.c:2983
```
#5  0x00728373 in g_signal_emit (instance=0x86aa7f8, signal_id=133, detail=0)

```
at gsignal.c:3040
```
#6  0x0013ee7b in mex_explorer_column_activated_cb (column=0x86bed00,

```
explorer=0x86aa7f8) at mex-explorer.c:496
```
#7  0x00728b8c in g_cclosure_marshal_VOID__VOID (closure=0x88d8be8,

```
return_value=0x0, n_param_values=1, param_values=0xae704fa8, 
invocation_hint=0xbfffdc70, marshal_data=0x0) at gmarshal.c:79
```
#8  0x0070cf04 in g_closure_invoke (closure=0x88d8be8, return_value=0x0,

```
n_param_values=1, param_values=0xae704fa8, invocation_hint=0xbfffdc70)
at gclosure.c:767
```
#9  0x0071f23a in signal_emit_unlocked_R (node=0x88b52e0, detail=0,

```
instance=0x86bed00, emission_return=0x0, instance_and_params=0xae704fa8)
at gsignal.c:3252
```
#10 0x007281ec in g_signal_emit_valist (instance=0x86bed00, signal_id=239,

```
detail=0, var_args=0xbfffde2c "\025\231/") at gsignal.c:2983
```
#11 0x00728373 in g_signal_emit (instance=0x86bed00, signal_id=239, detail=0)

```
at gsignal.c:3040
```
#12 0x001312fd in mex_column_header_clicked_cb (button=0x873dca8,

```
self=0x86bed00) at mex-column.c:1407
```

(gdb) p container
$2 = (ClutterActor *) 0x872f060
(gdb) p *container
$3 = {parent_instance = {g_type_instance = {g_class = 0x40000002}, 
    ref_count = 7509744, qdata = 0xbfffe824}, flags = 0, 
  private_flags = 134553984, priv = 0x51}

seems random memory to me.

And indeed the compiler dedects paths where container can be unitialized.
  CC     libmex_0.2_la-mex-explorer.lo
mex-explorer.c: In function 'mex_explorer_push_model':
mex-explorer.c:863:11: warning: 'container' may be used uninitialized in this function

Not quite sure what to do though, you are more familiar with this code

**Comment by ghost** [comment]
Fixed 9328ca48240a74426a411652cb2cc91dce92d747
