### ISSUE TITLE
Going back from playing a video, its thumbnail goes back to the place holder for a few frames

### ISSUE THREAD

**Issue by dlespiau** [media-explorer/media-explorer#69]
For some reason, when playing a video and then going back, you can see the thumbnail of the selected video go back to the generic place holder and then load the correct thumbnail again. This gives some bad flickering

**Comment by ghost** [comment]
Yep, spotted that one, it's due to the update of the last position in tracker coming back as an update event.

**Comment by ghost** [comment]
Fixed in 5c333b456f87d79f4ba478ca83f1ff03b68f1bc7
