### ISSUE TITLE
Should start as fullscreen by default

### ISSUE THREAD

**Issue by hadess** [media-explorer/media-explorer#75]
I'm not sure there's any reasons why we would want the application to start windowed, except for testing.

Add a --fullscreen option, and make it the default in the .desktop file would solve the problem nicely.

**Comment by Cwiiis** [comment]
We already have the option, so we just need to add it to the .desktop.

**Comment by semiot** [comment]
Will add to the 0.1.4 milestone...

**Comment by thos** [comment]
Full screen mode is already enabled by default in mex.desktop.
