### ISSUE TITLE
Hide "power" button by default

### ISSUE THREAD

**Issue by hadess** [media-explorer/media-explorer#77]
Mex has 2 running modes, one for embedded devices/set top boxes where it is the interface (and offers network config, etc.) and the power button actually powers off the machine, and "desktop" mode.

In "desktop" mode, the "power" button should either be removed (and remote/keyboard keys used to close the program) or just exit the application, not trigger a shutdown for the machine.

**Comment by ghost** [comment]
As of c0d70c7411150051d83d we no longer have the shutdown launcher and the button was previously changed to close the application and not run that launcher.

**Comment by thos** [comment]
The "power" button provides a way to close the application. It does not trigger a shutdown for the machine.
