### ISSUE TITLE
Use sensible default key bindings for the GNOME profile

### ISSUE THREAD

**Issue by dlespiau** [media-explorer/media-explorer#83]
Instead of asking the user for key bindings in the out of box experience, just ship with default key bindings and skip the configuration phase.

Proposed keys:

"Back" -> Escape
"Info" -> Menu
"Home" -> Home

**Comment by hadess** [comment]
You can call lirc_readconfig() multiple times, and have the later configs override the earlier ones. So you should ship a working LIRC config out of the box:
http://git.gnome.org/browse/totem/commit/src/plugins/lirc/totem-lirc.c?id=51c028727c6de2b858c89b046c6b657980a011dd

**Comment by thos** [comment]
The out-of-box experience no longer includes the key binding configuration steps.

**Comment by thos** [comment]
We may want to bind several keycodes to the same command. For example:

"Back" → Escape, XF86Back, XF86Close, BackSpace

**Comment by thos** [comment]
I've updated the application to add support for a few extra keycodes for each action. I've also updates the lirc configuration so that more buttons are supported.

**Comment by thos** [comment]
I've also added 'i' to the list of keys for the info button.

**Comment by dlespiau** [comment]
Thomas' work covers the scope of this bug, closing
