### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by and471** [media-explorer/media-explorer#9]
When I try to compile media-explorer (with ./autogen.sh && make) I get the following error

`make[2]: Entering directory `/tmp/media-explorer/player'
  CC     mex_media_player-main.o
  CCLD   mex-media-player
../mex/.libs/libmex-0.2.so: undefined reference to `mx_image_animate_scale_mode'
collect2: ld returned 1 exit status`

I am using Ubuntu 11.04 and the version of mx I have installed is 1.1.11

**Comment by rossburton** [comment]
You need 1.1.12 for that API.  Thanks for pointing this out, I've just bumped the configure check.
