### ISSUE TITLE
Add a "show fps" short cut in debug mode

### ISSUE THREAD

**Issue by dlespiau** [media-explorer/media-explorer#90]
Really handy to have the fps on-screen esp. on non desktop-class hardware.

**Comment by hadess** [comment]
As a debug? Maybe. If you're putting this in the main UI, I'll unleash the wrath of designers onto you.

**Comment by dlespiau** [comment]
let's be serious :p

Of course, the shortcut to show/hide that fps count will only be available if the debug plugin is loaded, not shown by default. (and this plugin is only compiled when compiling from the git tree)

**Comment by thos** [comment]
I implemented this in commit 410ce07, which can be merged into master once reviewed.

**Comment by dlespiau** [comment]
Pushed the branch in master, it works!
