### ISSUE TITLE
DVD playback

### ISSUE THREAD

**Issue by ghost** [media-explorer/media-explorer#94]
We almost have everything needed for dvd playback in mex - you can specify dvd:///mount/chapter on the clutter media uri that the mex player uses and it works fine\* we just need to provide an easier way to access it. 

*there's no way to get to the dvd top menu other than stopping and starting playback

**Comment by semiot** [comment]
Is there a way that when DVD is detected you can add an item to the top of the video panel?

**Comment by ghost** [comment]
Yes that should be possible. 

note to self - check mex-gio-notification-source to see if we can get notification of a video dvd being inserted/removed propagated to somewhere useful

**Comment by semiot** [comment]
Adding this to the Sept. Milestone

**Comment by ghost** [comment]
@llandwerlin42 check michael/optical-disk if you feel like reviewing, there are probably a couple of things I've missed.

**Comment by ghost** [comment]
Just one cosmetic comment :), otherwise it looks good, feel free to merge.

**Comment by ghost** [comment]
Merged
