### ISSUE TITLE
Web interface design

### ISSUE THREAD

**Issue by ghost** [media-explorer/media-explorer#99]
Implement new design for the mex web interface.

Pending @semiot to review and tweak new design

**Comment by ghost** [comment]
bug scrub

**Comment by semiot** [comment]
When: Thursday, August 02, 2012 7:00 PM-9:00 PM. (UTC) Dublin, Edinburgh, Lisbon, London
Where: 6th Floor

_~_~_~_~_~_~_~_~_~_

On Thursday, we'll be hosting the UX Bookclub (courtesy Matthew Sole).

The club will be interviewing Mike Monteiro, author of "Design is a Job" and having a few beers. We're all welcome to join.

More details below:

---

The London UX Bookclub returns to read and discuss Mike Monteiro's recently published diatribe: Design is a Job.

In this book, Mike looks at many of the aspects of being a designer we don't talk about so much, like how we work with clients and co-workers, how to present design and manage feedback, how to choose the right clients, and more.

It's a fairly short read and chock full of great discussion points - should make for a good UX Bookclub!

Thanks to our friends at Intel for hosting us - for the very first time! (Don't worry Intel, we're a friendly bunch).

## As usual, tickets are limited so please only take one if you REALLY intend to read the book and come along. People who don't show up on the night get bad UX Karma.

Intel Corporation (UK) Limited
Registered No. 1134945 (England)
Registered Office: Pipers Way, Swindon SN3 1RJ
VAT No: 860 2173 47

This e-mail and any attachments may contain confidential material for
the sole use of the intended recipient(s). Any review or distribution
by others is strictly prohibited. If you are not the intended
recipient, please contact the sender and delete all copies.
